version: '3.2'
services:
    openidserver:
        image: jboss/keycloak:4.8.3.Final
        hostname: openidserver
        expose:
            - 8080
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=RM99Q330Tg
            - KEYCLOAK_LOGLEVEL=DEBUG
            - DB_VENDOR=MYSQL
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=8HVcBB5FMv
            - MYSQL_PORT_3306_TCP_ADDR=mysql
            - MYSQL_PORT_3306_TCP_PORT=3306
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        hostname: mysql
        expose:
            - 3306
        volumes:
            - ./data/mysql/keycloak/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=KgWVt9jCUq
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=8HVcBB5FMv
