== Step 2: Write API Request Handling

Basic request handling flow

[plantuml,./assets/basic-request-handling, png]
....
actor User
autonumber

User -> Server: /session
activate Server
Server -> EventBus:	Send message on \n**OperationId** (Open API)
EventBus -> Service:	**OperationId** is mapped to \n**ServiceUnquieId**. Service \n\
listen on **ServiceUniqueId** \n for any API Request
Service --> EventBus:Service sends response \nas reply to EventBus Message
EventBus --> Server
Server --> User
deactivate Server
....

. Request Processing (Step 1 and 6) is synchronous.  In case Service fails to response
within predefined time limit (/io/vertx/core/eventbus/DeliveryOptions.sendTimeout).
request is canceled and fail response is sent back.
. For each operationId defined in Open API definition, a service is registered. Service
contains mapping of Operation Id and UniqueServiceId. Whenever request comes
it is converted into EventBus message and sent on UniqueServiceId (Steps 2-3).
. Step 2-5 are asynchronous.

=== Handle GET method called on /session URL

==== Create Service Class
[source,java,linenums]
----
include::./../src/main/java/in/erail/tutorial/SessionService.java[]
----

==== Create Service Component

Create below Component configuration file and place it in
*/config-layers/common/in/erail/tutorial/SessionService*

[source,ini,linenums]
----
include::./../config-layers/common/in/erail/tutorial/SessionService.properties[]
----

Add service to *OpenAPI3RouteBuilder*
[source,ini,linenums]
----
include::./../config-layers/common/in/erail/route/OpenAPI3RouteBuilder.properties[]
----

Our API is ready to use. Lets create a test class to test our service.

== Step 3: Write Test to test our service

[source,java,linenums]
----
include::./../src/test/java/in/erail/tutorial/SessionServiceTest.java[]
----
