
== Step 1:Create Open API 3 Service Definition

To make life easy, we have used https://studio.apicur.io[Apicurio] to create Open API 3
definition. Below is definition

.openapi3.json
[source,json,linenums]
----
include::./../config-layers/common/in/erail/route/openapi3.json[]
----

Our API will have single URL /session (like http://localhost:8080/session). Session is not
related to actual Vertx session. This session API support two methods.

.GET
On get request, session API will return all session messages.

.POST
To post any message in session, we can call post on session API. Post request payload will
contain message to be posted.

NOTE: Each method requiring processing must have *unique OperationId*. OperationId
is used for processing request from method.

=== Configure API Framework to use service definition

Copy openapi3.json to *config-layers/common/in/erail/route/openapi3.json*. Now
API Framework is configured to handle API Request. Next step is to write code to handle
request.
